learning_templates/basic_app/urls.py
from basic_app import views
from django.urls import path

app_name = 'basic_app'

urlpatterns = [
	path('relative/', views.relative, name="relative"),
	path('otherpage/', views.otherpage, name="otherpage"),
]
 

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.urls import path
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="IndexPage"),
    #path('basic_app/', include('basic_app.urls')),
    url(r'^basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

def index(request):
	context_dict = {'text':'hello World', 'number':100}
	return render(request,'basic_app/index.html',context_dict)
	
def otherpage(request):
	return render(request, 'basic_app/otherpage.html')

def relative(request):
	return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'IndexPage' %}">Brand Name</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:otherpage' %}">Other Page</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block base_block %}
        {% endblock %}
    </div>
</body>

</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block base_block %}

<h1>Welcome to Index Page</h1>
<h2>Index page is Showing.</h2>
<h1>{{ text|cut:'hello' }}</h1>
<h1>{{ number|add:"100" }}</h1>
{% endblock %}

learning_templates/templates/basic_app/otherpage.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block base_block %}
<h1>Welcome To Other</h1>
<h2>Example of template Inheritance</h2>
{%endblock%}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>

<head>
    <title></title>
</head>

<body>
    <h1>Welcome To relative URL Template Page</h1>
    <a href="{% url 'basic_app:otherpage' %}">This is Other Page</a>
    <a href="{% url 'admin:index' %}">Admin Text</a>
    <a href="{% url 'IndexPage' %}">to index</a>
</body>

</html>